language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - LARAVEL_VERSION=5.6.*
  - LARAVEL_VERSION=5.7.*
  - LARAVEL_VERSION=5.8.*

matrix:
  fast_finish: true

before_script:
  - composer update

script:
  - phpunit